# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Compile latex
      - name: TeXLive PDF
        uses: repaction/texlive@mini-v2
        with:
          # The LaTeX file to be compiled.
          tex_files: resume.tex
          # The LaTeX engine to be invoked.
          #compiler: # optional, default is latexmk
          # Arguments to be passed to the LaTeX engine
          #options: # optional, default is -pdf -cd -file-line-error -halt-on-error -interaction=nonstopmode
