# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Compile latex
      - name: TeXLive PDF
        uses: waisbrot/texlive@8619ac5ba97ad7c60c97d5e96459ae03d3f289d7
        with:
          tex_files: resume.tex
      - name: Get the date
        id: today
        run: echo "date=$(date --iso-8601=minutes)" >> "$GITHUB_OUTPUT"
      - name: Tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{steps.today.outputs.date}}
      - name: Publish
        uses: softprops/action-gh-release@c9b46fe7aad9f02afd89b12450b780f52dacfb2d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{steps.today.outputs.date}}
          tag_name: ${{steps.today.outputs.date}}
          draft: false
          prerelease: false
          files: resume.pdf
          fail_on_unmatched_files: true
