# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Compile latex
      - name: TeXLive PDF
        uses: waisbrot/texlive@985c8ab40f5373da33c67067ae17746941726ac4
        with:
          # The LaTeX file to be compiled.
          tex_files: resume.tex
          # The LaTeX engine to be invoked.
          #compiler: # optional, default is latexmk
          # Arguments to be passed to the LaTeX engine
          #options: # optional, default is -pdf -cd -file-line-error -halt-on-error -interaction=nonstopmode
      - name: Get the date
        uses: lee-dohm/calculate-dates-and-times@v1.0.2
        id: today
        with:
          # An amount and value to add to the current date, _ex:_ `2 days`
          #add: # optional
          # A format string correspending to the format function of moment.js
          format: YYYY-MM-DD
          # An amount and value to subtract from the current date, _ex:_ `3 weeks`
          #subtract: # optional
      - name: Tag
        uses: tvdias/github-tagger@v0.0.2
        with:
          # The GITHUB_TOKEN secret
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Tag text
          tag: ${{steps.today.outputs.date}}
          # optional commit sha to apply the tag to
          #commit-sha: # optional          
      - name: Publish
        # You may pin to the exact commit or the version.
        # uses: softprops/action-gh-release@b7e450da2a4b4cb4bfbae528f788167786cfcedf
        uses: softprops/action-gh-release@v0.1.5
        with:
          # Note-worthy description of changes in release
          #body: # optional
          # Path to load note-worthy description of changes in release from
          #body_path: # optional
          # Gives the release a custom name. Defaults to tag name
          name: ${{steps.today.outputs.date}}
          # Creates a draft release. Defaults to false
          draft: false
          # Identify the release as a prerelease. Defaults to false
          prerelease: false
          # Newline-delimited list of path globs for asset files to upload
          files: resume.tex
